/// Centralized Authentication & Password Policy Validation Utilities.
class PasswordValidationResult {
  final bool hasMinLength;
  final bool hasUppercase;
  final bool hasLowercase;
  final bool hasDigit;
  final bool hasSpecialChar;

  const PasswordValidationResult({
    required this.hasMinLength,
    required this.hasUppercase,
    required this.hasLowercase,
    required this.hasDigit,
    required this.hasSpecialChar,
  });

  /// Returns true if all 5 password security criteria are satisfied.
  bool get isValid =>
      hasMinLength &&
      hasUppercase &&
      hasLowercase &&
      hasDigit &&
      hasSpecialChar;
}

class AuthValidator {
  AuthValidator._();

  /// Standard RFC-compliant email regex pattern.
  static final RegExp _emailRegex = RegExp(
    r"^[\w\+\-\.]+@([\w-]+\.)+[\w-]{2,}$",
  );

  /// Trims whitespace and lowercases email address inputs so "User@Gmail.com"
  /// and "user@gmail.com" always map to the exact same account.
  static String normalizeEmail(String? email) {
    if (email == null) return '';
    return email.trim().toLowerCase();
  }

  /// Validates format of email address.
  static bool isValidEmail(String? email) {
    final normalized = normalizeEmail(email);
    if (normalized.isEmpty) return false;
    return _emailRegex.hasMatch(normalized);
  }

  /// Evaluates a password string against GoalForge security policy criteria:
  /// 1. At least 8 characters long
  /// 2. Contains at least one uppercase letter (A-Z)
  /// 3. Contains at least one lowercase letter (a-z)
  /// 4. Contains at least one numeric digit (0-9)
  /// 5. Contains at least one special character (non-alphanumeric, e.g. !@#$%^&*()_+-=[]{}|;:',.<>?/~\`)
  ///
  /// Note: The special character regex uses `[^a-zA-Z0-9]` (any non-alphanumeric char)
  /// to ensure passwords generated by password managers (e.g. 1Password, Bitwarden)
  /// containing symbols like `_`, `-`, `~`, `+`, `=` are never falsely rejected.
  static PasswordValidationResult validatePassword(String? password) {
    final pwd = password ?? '';
    final hasMinLength = pwd.length >= 8;
    final hasUppercase = RegExp(r'[A-Z]').hasMatch(pwd);
    final hasLowercase = RegExp(r'[a-z]').hasMatch(pwd);
    final hasDigit = RegExp(r'[0-9]').hasMatch(pwd);
    // Non-alphanumeric check accommodates all symbols including underscores, hyphens, and spaces
    final hasSpecialChar = RegExp(r'[^a-zA-Z0-9]').hasMatch(pwd);

    return PasswordValidationResult(
      hasMinLength: hasMinLength,
      hasUppercase: hasUppercase,
      hasLowercase: hasLowercase,
      hasDigit: hasDigit,
      hasSpecialChar: hasSpecialChar,
    );
  }

  /// Signup-only password validation message (returns null if valid, error string if invalid).
  static String? validateSignupPassword(String? password) {
    if (password == null || password.isEmpty) {
      return 'Please enter a password';
    }
    final result = validatePassword(password);
    if (!result.isValid) {
      return 'Password does not meet security requirements';
    }
    return null;
  }

  /// Login password validation (non-empty check ONLY to prevent locking out legacy accounts).
  static String? validateLoginPassword(String? password) {
    if (password == null || password.isEmpty) {
      return 'Please enter your password';
    }
    return null;
  }
}
