// File generated by FlutterFire CLI / GoalForge configuration.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLVEzvox1MIavOpSiONdM9MSzZ5EH_auI',
    appId: '1:328180873593:web:e642ee566084375feed7a8',
    messagingSenderId: '328180873593',
    projectId: 'goalforge-fcae0',
    authDomain: 'goalforge-fcae0.firebaseapp.com',
    storageBucket: 'goalforge-fcae0.firebasestorage.app',
    measurementId: 'G-VJ5M82BF9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANKPJHFXqpGta7RM8mBPZC9cBsmaSo5pc',
    appId: '1:328180873593:android:6ffbfc90ea63e20beed7a8',
    messagingSenderId: '328180873593',
    projectId: 'goalforge-fcae0',
    storageBucket: 'goalforge-fcae0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhoOkBR3EFK7hRha9jZiY7R7762ISgv7M',
    appId: '1:328180873593:ios:520d1e670a5dac3aeed7a8',
    messagingSenderId: '328180873593',
    projectId: 'goalforge-fcae0',
    storageBucket: 'goalforge-fcae0.firebasestorage.app',
    iosBundleId: 'com.example.goalforge',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhoOkBR3EFK7hRha9jZiY7R7762ISgv7M',
    appId: '1:328180873593:ios:520d1e670a5dac3aeed7a8',
    messagingSenderId: '328180873593',
    projectId: 'goalforge-fcae0',
    storageBucket: 'goalforge-fcae0.firebasestorage.app',
    iosBundleId: 'com.example.goalforge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLVEzvox1MIavOpSiONdM9MSzZ5EH_auI',
    appId: '1:328180873593:web:51b70d34ff7b455beed7a8',
    messagingSenderId: '328180873593',
    projectId: 'goalforge-fcae0',
    authDomain: 'goalforge-fcae0.firebaseapp.com',
    storageBucket: 'goalforge-fcae0.firebasestorage.app',
    measurementId: 'G-C4FZTDQRTH',
  );
}
