import '../domain/models/badge_model.dart';

class BadgesCatalog {
  BadgesCatalog._();

  static const List<BadgeDefinition> allBadges = [
    // ── CONSISTENCY BADGES (7) ──
    BadgeDefinition(
      id: 'streak_3',
      title: 'Ignition Spark',
      description: 'Maintain a 3-day active streak.',
      category: BadgeCategory.consistency,
      requirementType: BadgeRequirementType.streak,
      targetValue: 3,
      iconName: 'flame',
    ),
    BadgeDefinition(
      id: 'streak_7',
      title: 'Week Warrior',
      description: 'Sustain a 7-day uninterrupted streak.',
      category: BadgeCategory.consistency,
      requirementType: BadgeRequirementType.streak,
      targetValue: 7,
      iconName: 'zap',
    ),
    BadgeDefinition(
      id: 'streak_14',
      title: 'Fortnight Focus',
      description: 'Log activity for 14 consecutive days.',
      category: BadgeCategory.consistency,
      requirementType: BadgeRequirementType.streak,
      targetValue: 14,
      iconName: 'shield',
    ),
    BadgeDefinition(
      id: 'streak_30',
      title: 'Unstoppable Momentum',
      description: 'Complete a full 30-day streak cycle.',
      category: BadgeCategory.consistency,
      requirementType: BadgeRequirementType.streak,
      targetValue: 30,
      iconName: 'trophy',
    ),
    BadgeDefinition(
      id: 'streak_60',
      title: 'Iron Resolve',
      description: 'Maintain discipline for 60 straight days.',
      category: BadgeCategory.consistency,
      requirementType: BadgeRequirementType.streak,
      targetValue: 60,
      iconName: 'crown',
    ),
    BadgeDefinition(
      id: 'streak_90',
      title: 'Titan of Habits',
      description: 'Achieve a legendary 90-day streak.',
      category: BadgeCategory.consistency,
      requirementType: BadgeRequirementType.streak,
      targetValue: 90,
      iconName: 'award',
    ),
    BadgeDefinition(
      id: 'perfect_3',
      title: 'Hat-Trick Perfection',
      description: 'Achieve 100% daily accuracy 3 times.',
      category: BadgeCategory.consistency,
      requirementType: BadgeRequirementType.perfectDays,
      targetValue: 3,
      iconName: 'checkCircle',
    ),

    // ── LEARNING & TASKS BADGES (7) ──
    BadgeDefinition(
      id: 'task_1',
      title: 'First Step',
      description: 'Complete your very first task in GoalForge.',
      category: BadgeCategory.learning,
      requirementType: BadgeRequirementType.completedTasks,
      targetValue: 1,
      iconName: 'check',
    ),
    BadgeDefinition(
      id: 'task_10',
      title: 'Task Crusher',
      description: 'Complete 10 total tasks.',
      category: BadgeCategory.learning,
      requirementType: BadgeRequirementType.completedTasks,
      targetValue: 10,
      iconName: 'checkSquare',
    ),
    BadgeDefinition(
      id: 'task_25',
      title: 'Execution Engine',
      description: 'Complete 25 total tasks.',
      category: BadgeCategory.learning,
      requirementType: BadgeRequirementType.completedTasks,
      targetValue: 25,
      iconName: 'layers',
    ),
    BadgeDefinition(
      id: 'task_50',
      title: 'Productivity Architect',
      description: 'Complete 50 total tasks.',
      category: BadgeCategory.learning,
      requirementType: BadgeRequirementType.completedTasks,
      targetValue: 50,
      iconName: 'cpu',
    ),
    BadgeDefinition(
      id: 'task_100',
      title: 'Centurion Executor',
      description: 'Complete 100 total tasks.',
      category: BadgeCategory.learning,
      requirementType: BadgeRequirementType.completedTasks,
      targetValue: 100,
      iconName: 'star',
    ),
    BadgeDefinition(
      id: 'habit_10',
      title: 'Habit Builder',
      description: 'Complete 10 habit logs.',
      category: BadgeCategory.learning,
      requirementType: BadgeRequirementType.completedHabits,
      targetValue: 10,
      iconName: 'repeat',
    ),
    BadgeDefinition(
      id: 'habit_50',
      title: 'Routine Master',
      description: 'Complete 50 habit logs.',
      category: BadgeCategory.learning,
      requirementType: BadgeRequirementType.completedHabits,
      targetValue: 50,
      iconName: 'activity',
    ),

    // ── FOCUS BADGES (7) ──
    BadgeDefinition(
      id: 'focus_15',
      title: 'Deep Diver',
      description: 'Log 15 minutes of deep focus time.',
      category: BadgeCategory.focus,
      requirementType: BadgeRequirementType.focusMinutes,
      targetValue: 15,
      iconName: 'clock',
    ),
    BadgeDefinition(
      id: 'focus_60',
      title: 'Flow State Initiate',
      description: 'Accumulate 60 minutes of total focus time.',
      category: BadgeCategory.focus,
      requirementType: BadgeRequirementType.focusMinutes,
      targetValue: 60,
      iconName: 'timer',
    ),
    BadgeDefinition(
      id: 'focus_180',
      title: 'Hyper-Focus Master',
      description: 'Accumulate 180 minutes (3 hours) of focus.',
      category: BadgeCategory.focus,
      requirementType: BadgeRequirementType.focusMinutes,
      targetValue: 180,
      iconName: 'compass',
    ),
    BadgeDefinition(
      id: 'focus_300',
      title: 'Monk Mind',
      description: 'Accumulate 300 minutes (5 hours) of focus.',
      category: BadgeCategory.focus,
      requirementType: BadgeRequirementType.focusMinutes,
      targetValue: 300,
      iconName: 'sun',
    ),
    BadgeDefinition(
      id: 'focus_600',
      title: 'Deep Work Virtuoso',
      description: 'Accumulate 600 minutes (10 hours) of focus.',
      category: BadgeCategory.focus,
      requirementType: BadgeRequirementType.focusMinutes,
      targetValue: 600,
      iconName: 'sparkles',
    ),
    BadgeDefinition(
      id: 'focus_1200',
      title: 'Grand Focus Sovereign',
      description: 'Accumulate 1,200 minutes (20 hours) of focus.',
      category: BadgeCategory.focus,
      requirementType: BadgeRequirementType.focusMinutes,
      targetValue: 1200,
      iconName: 'globe',
    ),
    BadgeDefinition(
      id: 'perfect_7',
      title: 'Flawless Week',
      description: 'Achieve 7 perfect accuracy days.',
      category: BadgeCategory.focus,
      requirementType: BadgeRequirementType.perfectDays,
      targetValue: 7,
      iconName: 'target',
    ),

    // ── ACCURACY BADGES (6) ──
    BadgeDefinition(
      id: 'accuracy_perfect_1',
      title: 'Bullseye',
      description: 'Finish a day with 100% task completion.',
      category: BadgeCategory.accuracy,
      requirementType: BadgeRequirementType.perfectDays,
      targetValue: 1,
      iconName: 'disc',
    ),
    BadgeDefinition(
      id: 'accuracy_perfect_10',
      title: 'Precision Specialist',
      description: 'Log 10 perfect accuracy days.',
      category: BadgeCategory.accuracy,
      requirementType: BadgeRequirementType.perfectDays,
      targetValue: 10,
      iconName: 'crosshair',
    ),
    BadgeDefinition(
      id: 'accuracy_perfect_20',
      title: 'Sharpshooter',
      description: 'Log 20 perfect accuracy days.',
      category: BadgeCategory.accuracy,
      requirementType: BadgeRequirementType.perfectDays,
      targetValue: 20,
      iconName: 'eye',
    ),
    BadgeDefinition(
      id: 'xp_100',
      title: 'Initiate XP',
      description: 'Earn 100 total XP.',
      category: BadgeCategory.accuracy,
      requirementType: BadgeRequirementType.totalXP,
      targetValue: 100,
      iconName: 'trendingUp',
    ),
    BadgeDefinition(
      id: 'xp_500',
      title: 'Vanguard XP',
      description: 'Earn 500 total XP.',
      category: BadgeCategory.accuracy,
      requirementType: BadgeRequirementType.totalXP,
      targetValue: 500,
      iconName: 'barChart',
    ),
    BadgeDefinition(
      id: 'xp_1000',
      title: 'Millennium XP',
      description: 'Earn 1,000 total XP.',
      category: BadgeCategory.accuracy,
      requirementType: BadgeRequirementType.totalXP,
      targetValue: 1000,
      iconName: 'award',
    ),

    // ── MASTERY BADGES (7) ──
    BadgeDefinition(
      id: 'goal_1',
      title: 'Dream Realized',
      description: 'Complete your first goal to 100%.',
      category: BadgeCategory.mastery,
      requirementType: BadgeRequirementType.completedGoals,
      targetValue: 1,
      iconName: 'flag',
    ),
    BadgeDefinition(
      id: 'goal_3',
      title: 'Goal Conqueror',
      description: 'Complete 3 goals to 100%.',
      category: BadgeCategory.mastery,
      requirementType: BadgeRequirementType.completedGoals,
      targetValue: 3,
      iconName: 'map',
    ),
    BadgeDefinition(
      id: 'goal_5',
      title: 'Visionary Master',
      description: 'Complete 5 goals to 100%.',
      category: BadgeCategory.mastery,
      requirementType: BadgeRequirementType.completedGoals,
      targetValue: 5,
      iconName: 'bookmark',
    ),
    BadgeDefinition(
      id: 'goal_10',
      title: 'Legacy Builder',
      description: 'Complete 10 goals to 100%.',
      category: BadgeCategory.mastery,
      requirementType: BadgeRequirementType.completedGoals,
      targetValue: 10,
      iconName: 'castle',
    ),
    BadgeDefinition(
      id: 'xp_2500',
      title: 'High Sovereign XP',
      description: 'Earn 2,500 total XP.',
      category: BadgeCategory.mastery,
      requirementType: BadgeRequirementType.totalXP,
      targetValue: 2500,
      iconName: 'star',
    ),
    BadgeDefinition(
      id: 'xp_5000',
      title: 'Legendary Ascendant',
      description: 'Earn 5,000 total XP.',
      category: BadgeCategory.mastery,
      requirementType: BadgeRequirementType.totalXP,
      targetValue: 5000,
      iconName: 'shield',
    ),
    BadgeDefinition(
      id: 'xp_8000',
      title: 'GoalForge Supreme',
      description: 'Reach maximum Level 12 (8,000 XP).',
      category: BadgeCategory.mastery,
      requirementType: BadgeRequirementType.totalXP,
      targetValue: 8000,
      iconName: 'crown',
    ),
  ];
}
